---
- name: Adding metrics route information to metricsPublicURL
  modify_yaml:
    dest: "{{ openshift.common.config_base }}/master/master-config.yaml"
    yaml_key: assetConfig.metricsPublicURL
    yaml_value: "https://{{ openshift_metrics_hawkular_hostname}}/hawkular/metrics"
  notify: restart master
  tags:
    - update_master_config
